### ISSUE TITLE
Feature: WINEPREFIX

### ISSUE THREAD

**Issue by michalrus** [phantom-code/airwave#1]
Hey,

plugins work great, thank you. :heart: 

It would be really cool to be able to define a `WINEPREFIX` per each link. So, most probably, we'd need:

1. `setenv("WINEPREFIX", blah_blah");` to appear before [this `execl`](https://github.com/phantom-code/airwave/blob/a6c411162b6e92d0dc38ba01dd6b83c67f7345dc/plugin/masterunit.cpp#L67),

1. a third column in `~/.config/airwave/airwave.conf` (nb. what happens now if I put a `=` in dll/so name?),

1. a third column in the graphical configuration app.

I [did this today for `abique/vstbridge`](https://github.com/abique/vst-bridge/commit/2a854152380bcf399d894d59e2000fd28b4e7bac), but that seems a lot easier. Maybe it's not… :cat: Please, please, when you get a chance…

**Comment by phantom-code** [comment]
The feature is implemented in the new version (1.0.0).

**Comment by michalrus** [comment]
Great, thank you. :heart:
