### ISSUE TITLE
Current version no longer working

### ISSUE THREAD

**Issue by lunadog** [phantom-code/airwave#10]
I can't get the (previously working) podolski plugin to load in renoise. I get the following error:

Renoise Plugin Server LOG> VstPlugs: Trying to instantiate /home/james/.vst/airwave/Podolski.so
Airwave host endpoint, version 1.1.1error: wrong number of arguments: 3usage: Z:\usr\local\bin\airwave-host-32.exe.so <vst path> <port id> <log level> <log socket path>

**Comment by phantom-code** [comment]
Did you update the existing links after upgrading the airwave? It seems that you forgot to press the "update" tool button.

**Comment by lunadog** [comment]
Yep - that's the first thing I did. Then I deleted all the original links and remade them with the new version.. Maybe there's some old files about somewhere..

**Comment by lunadog** [comment]
ah - it was the old airwave-utility that I was running - didn't realise that had been superseded!
