### ISSUE TITLE
Installer Outdated

### ISSUE THREAD

**Issue by badunit** [phantom-code/airwave#100]
Installer is complete outdated...
First Steinberg change sdk folder structure, then steinberg also change vst2.x folder files names...
Like aeffect.h now is audioeffect.h  and so on...

When running 'make' command the installer fail.
(I've tried to rename all files like installer want (old file names), but installer don't find such files, or i don't know what error throw at me...)

**Comment by rodlie** [comment]
https://github.com/rodlie/airwave/pull/2#issuecomment-441390666

**Comment by badunit** [comment]
Thanks rodlie!
