### ISSUE TITLE
Loading VSTi in Muse 2.2.1 segfaults

### ISSUE THREAD

**Issue by lunadog** [phantom-code/airwave#11]
Crystal:

Error message:

FIXME: VstNativeSynthIF::queryPrograms(): effGetProgramNameIndexed returned 0. Used ugly effSetProgram/effGetProgramName instead
Segmentation fault

TyrellN6:
C:\users\james\Desktop\/TyrellN6.log 
no deskTopFile found 
Segmentation fault

Note: these are both 32 bit VSTi which Muse wouldn't even try to open in the past..

**Comment by phantom-code** [comment]
These error messages are not from the Airwave. Just checked, the Crystal plugin doesn't support the effGetProgramNameIndexed dispatch event, so nothing wrong here.
BTW, Crystal and TyrellN6 work with the Bitwig Studio at the first glance.
I'm not 100% sure, but it's probably a Muse issue. There is another (unrelated to Airwave) error report for the Muse: http://www.kvraudio.com/forum/viewtopic.php?p=6112194#p6112194
So even the native Linux VSTs don't work in it. Can you check these plugins in Renoise Tracker?

**Comment by asbaklm** [comment]
I'm experiencing something similar, will create a new issue, and it does seem to be airwave related. (Fault may be with Muse but interaction with airwave appears to lead to a crash)

**Comment by phantom-code** [comment]
I hope that this issue is fixed. If not, feel free to comment here of open another one.
