### ISSUE TITLE
Some plugins lockup in airwave but not wine

### ISSUE THREAD

**Issue by lunadog** [phantom-code/airwave#14]
A couple of plugins I have been trying recently have some problems with airwave - u-he Triple Cheese, and Archetype Instruments Locomotiv under Linux Renoise with Airwave. Both lockup when using airwave - either immediately at startup (Triple Cheese), or when choosing an instrument from the drop down panel (Locomotiv). There is the following message:

err:ntdll:RtlpWaitForCriticalSection section 0x7db07d64 "?" wait timed out in thread 0075, blocked by 0073, retrying (60 sec)

However, similar messages occur when running these plugins under the windows version of renoise under wine, but no lockups of the VSTi occur.

**Comment by phantom-code** [comment]
As far as I understand you got this issue with the latest changes in the develop branch. Please, rebuild from the develop branch and try again. I hope that I've fixed this issue.

**Comment by lunadog** [comment]
Yep - seems to be working now. Thanks!
