### ISSUE TITLE
default directories separators not working

### ISSUE THREAD

**Issue by joehannes** [phantom-code/airwave#18]
When trying to create a new Plugin it provides defaults for the vst dirs, separating them with the colon (:) ... this notation then isn't accepted when clicking ok

**Comment by phantom-code** [comment]
As far as I understood this issue, you have configured the VST_PATH environment variable with multiple directories, separated by the colons. In the current implementation only one "favorite" VST directory is supported ("VST location" in the settings dialog). I think I can use the first path from the VST_PATH if it has multiple values. I will fix this in the next version.

**Comment by joehannes** [comment]
Exactly, that is, Ubuntu did this probably and I actually thought you did it :) hehe ...
Yeah, but you read right in between the lines, getting there, thx!

**Comment by phantom-code** [comment]
I totally forget about that one, I'm sorry for that. I think I fixed it in the develop branch.
