### ISSUE TITLE
Nothing happens after Plugin created, no log output regardless the log level

### ISSUE THREAD

**Issue by joehannes** [phantom-code/airwave#20]
When I look at the video you provided via your [dropbox](https://dl.dropboxusercontent.com/u/33529975/airwave-usage.ogv) it looks to me the Plugin/Vst.so should be automatically created on finishing the setup ...
The Video shows instant log output and you straight head to Bitwig and find the wrapped native VST.

In my case nothing happens.
Regardless the log level (up to flood), not a single letter of output.
No .so file or whatever is created in the destination folder.
No output in the CL when starting airwave-manager from the CLI

**Comment by joehannes** [comment]
BTW ...
I'm on ubuntu 14.04.2 with KXStudio ppa:s
I got some extra hardware to my default laptop should that be somehow triggering whatever
Since I use KXStudio ppa:s I don't install wine1.7 as proposed in the README, but wine-rt, which boils down to 1.7.46 ...
All wine executables are in place as set in the config
All additional packages were installed as described in the README

**Comment by phantom-code** [comment]
You should have set VST directory in the Bitwig Studio to a place, where airwave manager creates its links (it's called "Link location" in the link creation dialog). The log messages will appear in the airwave manager as soon, as VST host (Bitwig Studio in this case) will scan these links. So, if you don't have the log messages, then it's likely that you've misconfigured something.
Please, ensure that .so files (links) are created in the same directory, where Bitwig Studio looks for the VST plugins. Don't move/rename any files manually (it won't work), only the airwave-manager should be used for link management tasks.

**Comment by joehannes** [comment]
Oh dear, so it actually takes a DAW scanning the dir for it to happen?!
I never thought it would be like that! I'll give it a shot in a sec, thx :)

**Comment by phantom-code** [comment]
I hope the issue is resolved for you.
