### ISSUE TITLE
How well do waves plugins work? 

### ISSUE THREAD

**Issue by spectromas** [phantom-code/airwave#21]
Curious about how well these work, have there been any reports about of the various sets of waves plugins?

**Comment by phantom-code** [comment]
As far as I know they should work good enough (I can't tell about the all bundle, but I have a report that Trans-X transient shaper works well). If in doubt, you can try Waves demo.

**Comment by spectromas** [comment]
Ok thanks, that's good to hear.

**Comment by opendeepin** [comment]
waves v9r2  working  on deepinlinux 

https://youtu.be/t38zZZFpP_M
