### ISSUE TITLE
Error compiling in debian wheezy 64-bit

### ISSUE THREAD

**Issue by DepreTux** [phantom-code/airwave#22]
Hi!

I'm getting the following error after make:
[  1%] Building CXX object src/plugin/CMakeFiles/airwave-plugin.dir/__/common/storage.cpp.o
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘bool Airwave::Storage::reload()’:
/home/fede/downloads/airwave/src/common/storage.cpp:37:16: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:42:16: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:104:17: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:118:17: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:148:15: error: ‘class std::map<std::basic_string<char>, Airwave::Storage::LinkInfo>’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Prefix Airwave::Storage::createPrefix(const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:281:30: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:281:48: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Loader Airwave::Storage::createLoader(const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:313:30: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:313:48: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Link Airwave::Storage::createLink(const string&, const string&, const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:360:28: error: ‘class std::map<std::basic_string<char>, Airwave::Storage::LinkInfo>’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:360:56: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘bool Airwave::Storage::Prefix::setName(const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:415:40: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:415:68: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘bool Airwave::Storage::Loader::setName(const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:506:40: error: ‘class std::map<std::basic_string<char>, std::basic_string<char> >’ has no member named ‘emplace’
/home/fede/downloads/airwave/src/common/storage.cpp:506:68: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘bool Airwave::Storage::Link::setPath(const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:604:30: error: ‘class std::map<std::basic_string<char>, Airwave::Storage::LinkInfo>’ has no member named ‘emplace_hint’
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Link Airwave::Storage::createLink(const string&, const string&, const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:366:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Loader Airwave::Storage::createLoader(const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:316:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/fede/downloads/airwave/src/common/storage.cpp: In member function ‘Airwave::Storage::Prefix Airwave::Storage::createPrefix(const string&, const string&)’:
/home/fede/downloads/airwave/src/common/storage.cpp:284:1: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: *** [src/plugin/CMakeFiles/airwave-plugin.dir/__/common/storage.cpp.o] Error 1
make[1]: *** [src/plugin/CMakeFiles/airwave-plugin.dir/all] Error 2
make: *** [all] Error 2

Any clues on how to fix this?

**Comment by phantom-code** [comment]
It seems that your gcc doesn't fully support c++11. You need a more fresh compiler or you can try pre-built deb package for ubuntu https://github.com/phantom-code/airwave/releases though I'm unsure if it will work with debian libraries.

**Comment by phantom-code** [comment]
I think I may close this for now. Feel free to reopen if you have a modern compiler and still get this issue.
