### ISSUE TITLE
Question: List of working plugins

### ISSUE THREAD

**Issue by jhenkins** [phantom-code/airwave#24]
Hello,

Is there somewhere a list of plugins that has been made to work with Airwave?

Thanks in advance!

**Comment by phantom-code** [comment]
I don't think that someone will create a plugin targeting the airwave. Though I heard that some developers are testing their plugins with WINE.

**Comment by kmatheussen** [comment]
There was a list of working/non-working windows vst plugins under linux once, but it seems to have dissapeared. 
Here's some trace:
https://web.archive.org/web/20100213155117/http://ladspavst.linuxaudio.org/?

**Comment by phantom-code** [comment]
This is not an issue, so I'm closing it.
