### ISSUE TITLE
Error on Fedora: libwinecrt0.a to format elf64-x86-64 is not supported

### ISSUE THREAD

**Issue by marko-lazic** [phantom-code/airwave#27]
```make
[ 42%] Building CXX object src/host/CMakeFiles/airwave-host-64.dir/host.cpp.o
[ 44%] Building CXX object src/host/CMakeFiles/airwave-host-64.dir/main.cpp.o
[ 45%] Linking CXX executable airwave-host-64
ld: Relocatable linking with relocations from format elf32-i386 (/usr/lib/wine/libwinecrt0.a(exe_entry.o)) to format elf64-x86-64 (airwave-host-64.Om9mXI.o) is not supported
winebuild: ld failed with status 1
winegcc: winebuild failed
src/host/CMakeFiles/airwave-host-64.dir/build.make:250: recipe for target 'src/host/airwave-host-64' failed
make[2]: *** [src/host/airwave-host-64] Error 2
CMakeFiles/Makefile2:179: recipe for target 'src/host/CMakeFiles/airwave-host-64.dir/all' failed
make[1]: *** [src/host/CMakeFiles/airwave-host-64.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Its on Fedora 23. I already had this app running on Fedora 22 perfectly. I moved /opt/airwave directory from old installation. 

P.S update main page. Fedora uses DNF instead of YUM, qt5-devel package is now qt5-qtbase-devel. I could commit changes my self but don't know if you(phantom-code) are cool with that. It is really small change.

**Comment by phantom-code** [comment]
Thanks for the information, I will uptate README file soon

**Comment by marko-lazic** [comment]
That makes sense. I will see where i messed up.

**Comment by marko-lazic** [comment]
I indeed missed: 
mingw64-wine-gecko noarch
 wine x86_64 
 wine-devel x86_64
That mistake was cause old qt5-devel package name took me of the safe rails. Anyway this problem is resolved. Hope i don't get into more road blocks.

**Comment by phantom-code** [comment]
I hope this issue is solved for you.
