### ISSUE TITLE
Airwave appears to crash Muse 2.2.1

### ISSUE THREAD

**Issue by asbaklm** [phantom-code/airwave#30]
There are a couple of issues:

- When loading a "native VST" in Muse (windows vsti hosted by airwave), Muse crashes immediately.
- When loading a DSSI-VST hosted Windows vsti in Muse, it works, until the vsti GUI is closed upon which Muse crashes. This happens when airwave is installed.

Once airwave is purged from system, Muse no longer crashes when closing DSSI-VST hosted vsti GUIs.

There seems to be some kind of interoperability issue between airwave and Muse, and even when airwave is not used as the vsti host, (eg DSSI-VST is used instead but airwave is installed) Muse still crashes.

Muse doesn't exhibit this kind of behaviour with the usual VST or DSSI-VST synths, it seems to be an issue unique to having airwave installed.

**Comment by phantom-code** [comment]
Is this issue still present for you?

**Comment by asbaklm** [comment]
I later found that the issue didn't affect latest Muse (compiled from sourcecode in github), so it hasn't affected me for some time.

I'll update to latest versions of Airwave and Muse and will let you know if there are any issues, many thanks for looking into this.

**Comment by asbaklm** [comment]
Updated to latest Git versions (12 March 2016) of Muse & Airwave, the problem doesn't exist with these recent builds. 
Not using Muse v.2.2.1 any longer, so cannot confirm whether this is still affected.

**Comment by phantom-code** [comment]
Thank you for report, I'll close this issue for now.
