### ISSUE TITLE
Forever indexing in Bitwig.

### ISSUE THREAD

**Issue by artur-shaik** [phantom-code/airwave#31]
Bitwig cannot recognize plugins that were added with airwave. It just show rotating icon with text `indexing /path/.vst` forever.

I tried to open plugins with carla, and it worked, even in bitwig, I could use windows `so` plugins from airwave through carla.

So, any issue with my enviroment?

**Comment by phantom-code** [comment]
Please, run the airwave-manager in the background while Bitwig doing its indexing and post the log messages somewhere.

**Comment by artur-shaik** [comment]
Ok, thanks for direction. Now I see that problem in `Oakmeal` plugin.

It work in carla, but doesn't load saved state, always reloading with init setup.

Anyway, here is logs: `http://pastebin.com/raw.php?i=wkimJqMn`

**Comment by phantom-code** [comment]
Yes, it seems that something went wrong at the plugin initialization stage. I will look closer a bit later.

**Comment by artur-shaik** [comment]
Thanks, here is two more line added in flood log level.
```
1448040684.747068081          Oatmeal.dll : handleAudioMaster(audioMasterVersion)
1448040684.753248685           Oatmeal.so : (0x7fd7936c3700) handleAudioMaster(opcode: audioMasterVersion, index: 0, value: 0, opt: 0)
```

**Comment by artur-shaik** [comment]
I now tried Oatmeal synth on `fix-audio-port2` branch, and it works. Thank you.

I think this can be closed after merge.

**Comment by phantom-code** [comment]
Thanks for the report!
