### ISSUE TITLE
Couldn't restore menu button after hiding

### ISSUE THREAD

**Issue by ahmadfarihan** [phantom-code/airwave#32]
Hi, I couldn't restore the menu buttons after accidentally hiding it.
Ubuntu 14.04 LTS.
Thanks for your good work!

**Comment by phantom-code** [comment]
Close the airwave manager program, then open its configuration file (${XDG_CONFIG_HOME/phantom-code/airwave-manager.conf) and remove line which starts form "windowState=". Or you can just delete this file (then you lose some of your settings).

**Comment by ahmadfarihan** [comment]
Thanks! It works.

**Comment by michalrus** [comment]
@ahmadfarihan, should this really be closed? @phantom-code, perhaps @ahmadfarihan should have been able to hide them in the first place? Or should've been able to restore them from withing the program. :cat:

**Comment by ahmadfarihan** [comment]
@michalrus I don't know man. Maybe I am too politically correct to leave it opened. I am just glad the software is usable. :thumbsup:

**Comment by phantom-code** [comment]
To be honset, I think I should disable the ability to hide the toolbar. It is enabled by default and I didn't even write a line of code to add it.

**Comment by michalrus** [comment]
@ahmadfarihan
![wat](http://i.imgur.com/jf7X9CR.jpg)
:smile_cat:
