### ISSUE TITLE
Order of host plugin instantiation

### ISSUE THREAD

**Issue by spamatica** [phantom-code/airwave#36]
Hi and thanks for this awesome software :)

I'm working on the MusE sequencer and finally got around to testing airwave. MusE has previously not been working with airwave the plugin instantiation crashed pretty much immediately.

Now, unfortunately I don't know enough about vst interaction but after some debugging and head scratching I found that when we instantiate VSTs in MusE, at one point we iterate through all the parameters (_plugin->getParameter(_plugin, i) ) , I believe to get their initial state. These calls crash instantly.
I found out that adding an initialization of the following parameters before the loop would fix it: effSetSampleRate, effSetBlockSize, effMainsChanged
I didn't examine exactly which one fixes it yet. I will probably add that as a fix for getting airwave to work in MusE but thought I would drop this here while I remember, in case it's a general issue in airwave. :)

Thanks

**Comment by phantom-code** [comment]
Hi, spamatica, and thanks for your report.
I think that you're right, it's likely an airwave regression after 7527ed243970fd551ba5115cfd29c94631334507 and I'll try to fix it soon. Meanwhile, could you try to checkout and build airwave from this point: 0c47ca25fef6142f7d700c9c4ea83d5d2b2b7651 ? Airwave will miss some useful automation events optimization, but the issue shouldn't be there.

**Comment by phantom-code** [comment]
Could you please build airwave from [fix-audio-port](https://github.com/phantom-code/airwave/commit/618b55ef484ae15528cc17e04fbbcc4bba80cb78) branch and test if this issue is fixed?

**Comment by spamatica** [comment]
Hi Anton,

Thanks for taking a look!
Unfortunately it does not seem like this fixes it. It still crashes when I
use this branch and comment my work around.

Regards,
Robert


2016-03-02 9:13 GMT+01:00 Anton Kalmykov <notifications@github.com>:

**Comment by phantom-code** [comment]
Could you post a backtrace somewhere?

**Comment by spamatica** [comment]
2016-03-02 16:18 GMT+01:00 Anton Kalmykov <notifications@github.com>:

> Could you post a backtrace somewhere?
>
Hey!
I'm really glad you asked.
While rebuilding I remembered that you had written to refresh the links
when upgrading. Not sure if it was that but testing now worked! I had three
plugins added and all of them open nicely now.

Thanks!
Robert

**Comment by phantom-code** [comment]
I'm glad to know that it works! Now I'm thinking to reimplement the latest change in a little different way. It would be nice if you test it one more time, I'll let you know when I finish it.

**Comment by phantom-code** [comment]
@spamatica please, build airwave from [fix-audio-port2](https://github.com/phantom-code/airwave/commit/b62af6e64a4b617311f6449dbb90fab94acebd9e) branch and test it again. I think that this patch is better than previous, but I need your confirmation before I merge it into the master.

**Comment by artur-shaik** [comment]
Just tried, for me it now work in Muse. Thank you.

**Comment by spamatica** [comment]
2016-03-03 15:06 GMT+01:00 Artur Shaik <notifications@github.com>:

> Just tried, for me it now work in Muse. Thank you.
>

Cool.


I tried now also and the instantiation seems working fine :)

I have trouble restoring settings also but for now I believe this is a MusE
issue.

Thanks,
Robert

**Comment by artur-shaik** [comment]
The same issue on restoring. Native vst restore all settings, but airwave always in init state.

**Comment by phantom-code** [comment]
Thanks for testing, I'll merge changes soon. I don't have a restore issue with Bitwig Studio, this one needs additional investigation.
