### ISSUE TITLE
Sound almost granulated

### ISSUE THREAD

**Issue by ellrazor** [phantom-code/airwave#37]
The sound I get from alot of plugins is not the same as Windows. Is this to do with Wine>?

thanks

**Comment by phantom-code** [comment]
It's hard to say due to a gazillion of different hosts, plugins, linux distributions and wine builds. Could you please provide some more information about your configuration?

**Comment by ellrazor** [comment]
I have tried using reaper and the same vst and it sounds fine

**Comment by phantom-code** [comment]
Could you please provide more information about your configuration. Linux distribution, VST host, used VST plugin(s) and wine version?

**Comment by phantom-code** [comment]
Closing this as I don't get a response. Reopen if needed.
