### ISSUE TITLE
Massive 32-Bit Wine Prefix

### ISSUE THREAD

**Issue by tortib** [phantom-code/airwave#47]
I created a wineprefix for 32bit by running WINEARCH=win32 WINEPREFIX=~/.wine32 wine wineboot but it doesn't seem to allow me to select the 32 Bit prefix so I can use it with Massive.dll 32-bit in Bitwig.  It keeps using the default wineprefix and it gives the following error when bitwig tries to scan massive.so.

1469211092.410206012           Massive.so : Initializing plugin endpoint 1.3.2
1469211092.410216144           Massive.so : Plugin binary: /home/tortib/Bitwig Studio/Library/Plugins/Massive.so
1469211092.410221058           Massive.so : WINE prefix:   /home/tortib/.wine
1469211092.410224964           Massive.so : WINE loader:   /usr/bin/wine
1469211092.410885027           Massive.so : VST binary:    /home/tortib/.wine/drive_c/Program Files/VST32/Massive.dll
1469211092.422731241           Massive.so : Host binary:   /usr/bin/airwave-host-32.exe
1469211092.422735577           Massive.so : Log level:     debug
1469211092.422737133           Massive.so : Main thread id: 0x7fa54859e740
1469211092.422853822           Massive.so : Child process started, pid=10421
1469211092.423067295           Massive.so : Callback thread started
1469211092.423078733           Massive.so : Waiting response from host endpoint...
1469211092.585732984          Massive.dll : Initializing host endpoint 1.3.2
1469211092.585740739          Massive.dll : Main thread id: 0x9
1469211093.152614607          Massive.dll : Waiting for plugin endpoint request...
1469211093.152631166          Massive.dll : Request from plugin endpoint received, sending response
1469211093.152637129          Massive.dll : Initializing VST plugin...
1469211093.375493834          Massive.dll : Unable to initialize VST plugin
1469211093.378550296          Massive.dll : Unable to initialize host endpoint
1469211093.379357801           Massive.so : Child process terminated

**Comment by phantom-code** [comment]
Have you added your new wineprefix in airwave settings?
![wineprefix](https://cloud.githubusercontent.com/assets/8014057/17069819/5b5ab94c-5061-11e6-80f2-8c23a5088baf.png)

**Comment by tortib** [comment]
I set the wine32 prefix that I created and it still has the same results.  Someone I know got this to work with a 64bit prefix.  I get the same output when using the wine32 prefix.

**Comment by phantom-code** [comment]
Hmmm.. it seems that you've installed Massive into the default wine prefix: /home/tortib/.wine/drive_c/Program Files/VST32/Massive.dll

You need to run NI Massive installer in the same way as you created your 32-bit wineprefix: WINEPREFIX=~/.wine32 <path/to/setup.exe>

**Comment by tortib** [comment]
I am loading the module from the 32 bit prefix.

1469318581.992144442           Massive.so : Initializing plugin endpoint 1.3.2
1469318581.992153996           Massive.so : Plugin binary: /home/tortib/Bitwig Studio/Library/Plugins/Massive.so
1469318581.992159043           Massive.so : WINE prefix:   /home/tortib/.wine32
1469318581.992164605           Massive.so : WINE loader:   /usr/bin/wine
1469318581.992169280           Massive.so : VST binary:    /home/tortib/.wine32/drive_c/Program Files/VST32/Massive.dll
1469318581.994617396           Massive.so : Host binary:   /usr/bin/airwave-host-32.exe
1469318581.994629477           Massive.so : Log level:     debug
1469318581.994633435           Massive.so : Main thread id: 0x7fd8413ae740
1469318581.994808319           Massive.so : Child process started, pid=5255
1469318581.996978273           Massive.so : Callback thread started
1469318581.996994670           Massive.so : Waiting response from host endpoint...
1469318582.416938843          Massive.dll : Initializing host endpoint 1.3.2
1469318582.416946676          Massive.dll : Main thread id: 0x9
1469318582.950670492          Massive.dll : Waiting for plugin endpoint request...
1469318582.950680286          Massive.dll : Request from plugin endpoint received, sending response
1469318582.950685144          Massive.dll : Initializing VST plugin...
1469318583.200899087          Massive.dll : Unable to initialize VST plugin
1469318583.202853546          Massive.dll : Unable to initialize host endpoint
1469318583.203623686           Massive.so : Child process terminated

**Comment by tortib** [comment]
I got it to work I had to run the installer instead of just using the DLL from my Komplete 9 install.  Thanks!

**Comment by phantom-code** [comment]
You're welcome, glad it helped!
