### ISSUE TITLE
Any hints regarding latency, XRUNs?

### ISSUE THREAD

**Issue by michalrus** [phantom-code/airwave#50]
So I noticed that—when using some Airwave plugin—I can only get down to 5.33 ms latency (128 frames, 2 periods).

In htop, I can see JACK, Ardour, airwave-host-*.exe and other wine-related processes (explorer.exe?) all running with RT priority (I’m using an RT kernel).

I was testing my favorite rhodes, MrRay73 Mark II, and even changing the latency to 4 ms results in looots of XRUNs. However, e.g. running our native rhodes, mda ePiano, as an LV2 plugin, I can get down to 2.67 ms (64 frames, 2 periods) with no XRUNs.

* Kernel: Linux nixos 4.4.15-rt23 #1-NixOS SMP PREEMPT RT Mon Jul 11 16:31:24 UTC 2016 x86_64 GNU/Linux
* Wine: wine-1.8.3 (with your xembed patch)
* Airwave: 1.3.2

Is there anything else I can do, or is it just it and, when playing rhodes, I have to live with 5.33 ms? =) (Yes, I certainly can recognize the difference, just did A/B blind tests with my brother! :smile_cat: ).

**Comment by phantom-code** [comment]
Honestly, I wonder how fast it performs right now. I doubt that you can decrease a latency even more, because 5.33 ms is already a very low one (taking into account what happens under the hood). I'm sorry, but I think that only an OS change could help you.

**Comment by michalrus** [comment]
Oookay. :smiley_cat: 

Thank you for this great project once more!

**Comment by phantom-code** [comment]
You're welcome!
