### ISSUE TITLE
Failure to compile: recipe for target 'all' failed

### ISSUE THREAD

**Issue by SammDu** [phantom-code/airwave#61]
I've followed all ur steps, typed **"make"**, it processed well at first, but then i ran into this error:

    [ 32%] Linking CXX executable airwave-host-64
    winebuild: gcc-4.7 failed with status 1
    winegcc: winebuild failed
    src/host/CMakeFiles/airwave-host-64.dir/build.make:250: recipe for target 'src/host/airwave-host-64' failed
    make[2]: *** [src/host/airwave-host-64] Error 2
    CMakeFiles/Makefile2:142: recipe for target 'src/host/CMakeFiles/airwave-host-64.dir/all' failed
    make[1]: *** [src/host/CMakeFiles/airwave-host-64.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
***
I'm running a 64bit ubuntu-gnome OS...plz help! Thanks in advance!

**Comment by SammDu** [comment]
Anyone here possibly help?

**Comment by phantom-code** [comment]
Is this all error messages? I see only the fact that build was failed, but no description of any reason. Do you have all 32-bit and 64-bit dependencies installed? Do you use multilib gcc (the one, which can generate machine code for both 32/64 bit architectures)? Do you have "development" versions of dependency packages installed?
What Linux distribution do you use, by the way? You can download pre-built package for Ubuntu from here: https://github.com/phantom-code/airwave/releases/tag/1.3.3

**Comment by SammDu** [comment]
Thanks i didn't realize theres binary packages...i'll try them out

**Comment by SammDu** [comment]
It worked! Pretty well so far :-)
Thanks dude!

**Comment by SammDu** [comment]
...Despite the fact that some characters coudn't be displayed correctly...or sometimes couldn't be displayed at all; and it usually happens with dropdown menus--which seems like a font issue. I can still see the functionality of that particular controll by...well...clicking on it, but it'd be so nice if i could just see the text and have an idea of what i am doing.

**Comment by phantom-code** [comment]
You're welcome!
There are ton of different VST plugins, also some of them require additional packages to be installed (in your case it may be gdiplus or even some fonts). And some plugins don't work at all (because of wine).

**Comment by SammDu** [comment]
I figured out that after i copied all fonts from my windows partition to `~/.wine/drive_c/windows/Fonts` the vsts can display texts again!
All problems solved thx dude~
