### ISSUE TITLE
Serum No GUI.

### ISSUE THREAD

**Issue by Glitch-is** [phantom-code/airwave#62]
I've managed to install serum, but when I launch it in my DAW I can't see Serum's GUI. I can play audio through the VST and when I click where the Serum's on-screen piano is I can actually play notes just fine. So it's not frozen, It's just not rendering the GUI.

I have have installed GDI+ and tried to override d2d1.dll in my wine config but still get the same result.

I'm using Arch Linux with i3 as a window manager.

**Comment by phantom-code** [comment]
This is not an airwave issue. I'd say this is a wine problem. Are you sure you have the right d2d1.dll version?
You need this one (32-bit):
version: 6.1.7601.17514
size: 827904 bytes
md5 hash: 3e0a1bf9e17349a8392455845721f92f

**Comment by Glitch-is** [comment]
Thanks! I just had the wrong version of d2d1.dll :+1:

**Comment by phantom-code** [comment]
Glad it helped!
