### ISSUE TITLE
NI products registration issue

### ISSUE THREAD

**Issue by quinton-ashley** [phantom-code/airwave#74]
I just downloaded Komplete 9 using virtualbox 32-bit Windows 10 and transferred everything to my 32-bit wine prefix and all the NI products that are listed as working work really well.  Unfortunately, I can't use Native Access or Service Center to register them.  I've scoured forums but can't seem to find answers.  I know this isn't related to the app but were you able to register NI products in wine?

**Comment by phantom-code** [comment]
Sadly I can't tell because I don't own any NI products
