### ISSUE TITLE
Sylenth1 version 2.0 - wine crashes when opened

### ISSUE THREAD

**Issue by thegoldgoat** [phantom-code/airwave#78]
I already copied d2d1.dll in system32 wine folder and chose 'Native, Builtin' from winecfg, but it doesn't work.
Here is the log from airwave magager:

1497375410.809551222          Sylenth1.so : Initializing plugin endpoint 1.3.3
1497375410.809570568          Sylenth1.so : Plugin binary: /home/andrea/vst/Sylenth1.so
1497375410.809586493          Sylenth1.so : WINE prefix:   /home/andrea/.wine
1497375410.809601579          Sylenth1.so : WINE loader:   /usr/bin/wine
1497375410.809616176          Sylenth1.so : VST binary:    /home/andrea/.wine/drive_c/Program Files (x86)/VstPlugins/Sylenth1/Sylenth1.dll
1497375410.810867128          Sylenth1.so : Host binary:   /opt/airwave/bin/airwave-host-32.exe
1497375410.810880677          Sylenth1.so : Main thread id: 0x7f334a15a740
1497375410.811236386          Sylenth1.so : Child process started, pid=4915
1497375410.811914698          Sylenth1.so : Callback thread started
1497375410.811964845          Sylenth1.so : Waiting response from host endpoint...
1497375410.973663924         Sylenth1.dll : Initializing host endpoint 1.3.3
1497375410.973673772         Sylenth1.dll : Main thread id: 0x2f
1497375410.998187575         Sylenth1.dll : Waiting for plugin endpoint request...
1497375410.998205385         Sylenth1.dll : Request from plugin endpoint received, sending response
1497375410.998217049         Sylenth1.dll : Initializing VST plugin...
1497375410.998221728         Sylenth1.dll : handleAudioMaster(audioMasterVersion)
1497375410.998304981          Sylenth1.so : (0x7f332ffff700) handleAudioMaster(opcode: audioMasterVersion, index: 0, value: 0, opt: 0)
1497375411.040374372         Sylenth1.dll : VST plugin is initialized
1497375411.040392392         Sylenth1.dll : Host endpoint is initialized
1497375411.040400005          Sylenth1.so : VST plugin summary:
1497375411.040409363          Sylenth1.so :   flags:         0x00001131
1497375411.040415649          Sylenth1.so :   program count: 512
1497375411.040418233          Sylenth1.so :   param count:   243
1497375411.040421097          Sylenth1.so :   input count:   0
1497375411.040425357          Sylenth1.so :   output count:  2
1497375411.040428500          Sylenth1.so :   initial delay: 0
1497375411.040430596          Sylenth1.so :   unique ID:     0x73796C31
1497375411.040433599          Sylenth1.so :   version:       1
1497375411.040437440          Sylenth1.so : Plugin endpoint is initialized
1497375411.040452945          Sylenth1.so : (0x7f334a15a740) dispatch: effGetVstVersion
1497375411.040467123         Sylenth1.dll : handleDispatch: effGetVstVersion
1497375411.040480184          Sylenth1.so : (0x7f334a15a740) dispatch: effGetPlugCategory
1497375411.040509029         Sylenth1.dll : handleDispatch: effGetPlugCategory
1497375411.040537874         Sylenth1.dll : handleDispatch: effOpen
1497375411.040548769          Sylenth1.so : Setting block size to 256 frames
1497375411.040583970         Sylenth1.dll : handleDispatch: effSetBlockSize
1497375411.040804743         Sylenth1.dll : Audio thread started
1497375411.040826115          Sylenth1.so : (0x7f334a15a740) dispatch: effSetSampleRate
1497375411.040850769         Sylenth1.dll : handleDispatch: effSetSampleRate
1497375411.040863062          Sylenth1.so : (0x7f334a15a740) dispatch: effSetBlockSize
1497375411.040867951          Sylenth1.so : Setting block size to 1024 frames
1497375411.040898472         Sylenth1.dll : handleDispatch: effSetBlockSize
1497375411.140877646         Sylenth1.dll : Audio thread terminated
1497375411.141242434         Sylenth1.dll : Audio thread started1497375470.023241778          Sylenth1.so : Child process terminated

1497375411.141394342          Sylenth1.so : (0x7f334a15a740) dispatch: effCanDo
1497375411.141441905         Sylenth1.dll : handleDispatch: effCanDo
1497375411.141456013          Sylenth1.so : (0x7f334a15a740) dispatch: effCanDo
1497375411.141472775         Sylenth1.dll : handleDispatch: effCanDo
1497375411.141483601          Sylenth1.so : (0x7f334a15a740) dispatch: effCanDo
1497375411.141497849         Sylenth1.dll : handleDispatch: effCanDo
1497375411.141513843          Sylenth1.so : (0x7f334a15a740) dispatch: effGetPlugCategory
1497375411.141521316         Sylenth1.dll : handleDispatch: effGetPlugCategory
1497375411.141537519          Sylenth1.so : (0x7f334a15a740) dispatch: effMainsChanged
1497375411.141553234         Sylenth1.dll : handleDispatch: effMainsChanged
1497375411.141557844         Sylenth1.dll : handleAudioMaster(audioMasterWantMidi)
1497375411.141568320          Sylenth1.so : (0x7f332ffff700) handleAudioMaster(opcode: audioMasterWantMidi, index: 0, value: 1, opt: 0)

Here is the log from wine:
Unhandled exception: page fault on read access to 0x7b8b7000 in 32-bit code (0x10087e98).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:10087e98 ESP:0032f4fc EBP:0032f504 EFLAGS:00210202(  R- --  I   - - - )
 EAX:00750000 EBX:7b811000 ECX:00000040 EDX:00000000
 ESI:7b8b7000 EDI:007f6000
Stack dump:
0x0032f4fc:  000a8000 00000000 0032f534 10087f51
0x0032f50c:  00750000 7b811000 000a8000 00750000
0x0032f51c:  00000000 0032f534 7b811000 7b8b92dc
0x0032f52c:  000a8000 7b811000 7b810000 100214cf
0x0032f53c:  00750000 7b811000 000a8000 00000000
0x0032f54c:  00e058c8 00e05410 7b87ace0 7b810138
Backtrace:
=>0 0x10087e98 in sylenth1 (+0x87e98) (0x0032f504)
  1 0x10087f51 in sylenth1 (+0x87f50) (0x0032f534)
  2 0x100214cf in sylenth1 (+0x214ce) (0x7b810000)
  3 0x00000003 (0x00905a4d)
0x10087e98: movq	0x0(%esi),%mm0
Modules:
Module	Address			Debug info	Name (92 modules)
PE	10000000-1030b000	Export          sylenth1
ELF	7b800000-7ba63000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba63000	\               kernel32
ELF	7bc00000-7bcf2000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcf2000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7e68f000-7e6b3000	Deferred        imm32<elf>
  \-PE	7e6a0000-7e6b3000	\               imm32
ELF	7e71e000-7e748000	Deferred        libexpat.so.1
ELF	7e748000-7e791000	Deferred        libfontconfig.so.1
ELF	7e791000-7e7bc000	Deferred        libpng12.so.0
ELF	7e7bc000-7e7d7000	Deferred        libz.so.1
ELF	7e7d7000-7e887000	Deferred        libfreetype.so.6
ELF	7e8ae000-7e923000	Deferred        advapi32<elf>
  \-PE	7e8c0000-7e923000	\               advapi32
ELF	7e923000-7ea3e000	Deferred        gdi32<elf>
  \-PE	7e930000-7ea3e000	\               gdi32
ELF	7ea3e000-7eb8e000	Deferred        user32<elf>
  \-PE	7ea50000-7eb8e000	\               user32
ELF	7eb8e000-7ebab000	Deferred        libgcc_s.so.1
ELF	7ed2f000-7ed49000	Deferred        version<elf>
  \-PE	7ed30000-7ed49000	\               version
ELF	7ef49000-7ef5c000	Deferred        libnss_files.so.2
ELF	7ef5c000-7ef69000	Deferred        libnss_nis.so.2
ELF	7ef69000-7ef84000	Deferred        libnsl.so.1
ELF	7ef84000-7efd9000	Deferred        libm.so.6
ELF	7efe3000-7f000000	Deferred        airwave-host-32<elf>
  \-PE	7eff0000-7f000000	\               airwave-host-32
ELF	f6227000-f623d000	Deferred        libgpg-error.so.0
ELF	f623d000-f62b2000	Deferred        libpcre.so.3
ELF	f62b2000-f6361000	Deferred        libgcrypt.so.20
ELF	f6361000-f6387000	Deferred        liblzma.so.5
ELF	f6387000-f6390000	Deferred        librt.so.1
ELF	f6390000-f63b6000	Deferred        libselinux.so.1
ELF	f63b6000-f6444000	Deferred        libsystemd.so.0
ELF	f6444000-f644d000	Deferred        libffi.so.6
ELF	f644d000-f6466000	Deferred        libresolv.so.2
ELF	f6466000-f646b000	Deferred        libkeyutils.so.1
ELF	f646b000-f64c5000	Deferred        libdbus-1.so.3
ELF	f64c5000-f6551000	Deferred        libgmp.so.10
ELF	f6551000-f6586000	Deferred        libhogweed.so.4
ELF	f6586000-f65c3000	Deferred        libnettle.so.6
ELF	f65c3000-f65d8000	Deferred        libtasn1.so.6
ELF	f65d8000-f660c000	Deferred        libidn.so.11
ELF	f660c000-f666d000	Deferred        libp11-kit.so.0
ELF	f666d000-f667a000	Deferred        libkrb5support.so.0
ELF	f667a000-f667f000	Deferred        libcom_err.so.2
ELF	f667f000-f66b0000	Deferred        libk5crypto.so.3
ELF	f66b0000-f6786000	Deferred        libkrb5.so.3
ELF	f6786000-f68de000	Deferred        libgnutls.so.30
ELF	f68de000-f6930000	Deferred        libgssapi_krb5.so.2
ELF	f6930000-f69b7000	Deferred        libcups.so.2
ELF	f69de000-f6a16000	Deferred        uxtheme<elf>
  \-PE	f69e0000-f6a16000	\               uxtheme
ELF	f6a16000-f6a1d000	Deferred        libxfixes.so.3
ELF	f6a1d000-f6a28000	Deferred        libxcursor.so.1
ELF	f6a28000-f6a3b000	Deferred        libxi.so.6
ELF	f6a3b000-f6a3f000	Deferred        libxcomposite.so.1
ELF	f6a3f000-f6a4c000	Deferred        libxrandr.so.2
ELF	f6a4c000-f6a58000	Deferred        libxrender.so.1
ELF	f6a58000-f6a5f000	Deferred        libxxf86vm.so.1
ELF	f6a5f000-f6a66000	Deferred        libxdmcp.so.6
ELF	f6a66000-f6a8c000	Deferred        libxcb.so.1
ELF	f6a8c000-f6bd7000	Deferred        libx11.so.6
ELF	f6bd7000-f6bec000	Deferred        libxext.so.6
ELF	f6bef000-f6c03000	Deferred        libavahi-client.so.3
ELF	f6c03000-f6c11000	Deferred        libavahi-common.so.3
ELF	f6c13000-f6ca2000	Deferred        winex11<elf>
  \-PE	f6c20000-f6ca2000	\               winex11
ELF	f6ca2000-f6d21000	Deferred        rpcrt4<elf>
  \-PE	f6cb0000-f6d21000	\               rpcrt4
ELF	f6d21000-f6e58000	Deferred        ole32<elf>
  \-PE	f6d40000-f6e58000	\               ole32
ELF	f6e58000-f6e97000	Deferred        winspool<elf>
  \-PE	f6e60000-f6e97000	\               winspool
ELF	f6e97000-f6f92000	Deferred        comctl32<elf>
  \-PE	f6ea0000-f6f92000	\               comctl32
ELF	f6f92000-f7009000	Deferred        shlwapi<elf>
  \-PE	f6fa0000-f7009000	\               shlwapi
ELF	f7009000-f7245000	Deferred        shell32<elf>
  \-PE	f7020000-f7245000	\               shell32
ELF	f7245000-f732e000	Deferred        comdlg32<elf>
  \-PE	f7250000-f732e000	\               comdlg32
ELF	f7359000-f750f000	Deferred        libc.so.6
ELF	f750f000-f7514000	Deferred        libdl.so.2
ELF	f7515000-f7532000	Deferred        libpthread.so.0
ELF	f7536000-f7540000	Deferred        libnss_compat.so.2
ELF	f7541000-f7545000	Deferred        libxinerama.so.1
ELF	f7545000-f7549000	Deferred        libxau.so.6
ELF	f7559000-f7710000	Dwarf           libwine.so.1
ELF	f7712000-f7737000	Deferred        ld-linux.so.2
ELF	f7739000-f773a000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 winecfg.exe
	00000009    0
0000000e services.exe
	0000001e    0
	0000001d    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001c    0
	00000019    0
	00000018    0
	00000013    0
0000001a plugplay.exe
	00000020    0
	0000001f    0
	0000001b    0
00000021 explorer.exe
	00000025    0
	00000024    0
	00000023    0
	00000022    0
00000026 winecfg.exe
	00000027    0
0000002e (D) Z:\opt\airwave\bin\airwave-host-32.exe
	00000031    0
	0000002f    0 <==
System information:
    Wine build: wine-1.8
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.8.0-54-generic

**Comment by phantom-code** [comment]
You need to use Sylenth1 version 3.xx. Version 2.xx doesn't work with wine.
