### ISSUE TITLE
Scrolling doesn't work

### ISSUE THREAD

**Issue by ghost** [phantom-code/airwave#9]
I guess you are aware of it. But I thought I might bring it up. Scrolling simply doesn't work.

**Comment by phantom-code** [comment]
Yes, this is the known issue, but from my point of view this is the WINE issue. For example, right after the start of NI FM8 in the Cocos Reaper the mouse wheel scrolling works. But if I click somewhere in plugin's window (make it active), scrolling stops to work. But I will investigate it more precisely.

**Comment by phantom-code** [comment]
I close this one because scrolling seems to be working in general. Only several plugins have issues with it and it's more likely a wine bug.
